version: '3.8'

services:
  frontend:
    build: .
    container_name: url-screenshot-frontend
    ports:
      - "8081:80"
    networks:
      - app-network  # Подключаемся к общей сети

networks:
  app-network:
    external: true  # Убедитесь, что сеть уже создана
